# https://docs.github.com/ja/github/administering-a-repository/configuration-options-for-dependency-updates#
version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  ignore:
  - dependency-name: aws/*
    update-types: ["version-update:semver-patch"]
  open-pull-requests-limit: 10
